name: Build

on: [push, pull_request]

jobs:
  build-platformio:
    runs-on: ubuntu-latest
    name: Sprinkl CI
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install platformio
      - name: Run PlatformIO
        run: python -m platformio run
